- hosts: all
  become: true
  tasks:
        - name: Install package
          yum:
              name: httpd
              state: installed
        
        - name: Restart the package
          service:
                  name: httpd
                  state: started
